---
title: "metExplore: Explore The Met Collection API"
output: rmarkdown::html_vignette
author: "Jiaqi Yao"
vignette: >
  %\VignetteIndexEntry{metExplore: Explore The Met Collection API}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```


```{r}
library(metExplore)
library(dplyr)
library(ggplot2)

```


```{r}
deps <- met_departments()
deps

```

```{r}
dept_id <- deps$department_id[1]
dept_id

```

```{r}
res_search <- met_search(
  q = "cat",
  has_images = TRUE,
  department_id = dept_id
)

attr(res_search, "total")
head(res_search, 10)

```


```{r}
if (nrow(res_search) == 0) {
  res_search <- met_search(q = "cat", has_images = TRUE)
}

attr(res_search, "total")
head(res_search, 10)


```

```{r}
one_id <- res_search$object_id[1]
one_id

```


```{r}
obj_one <- met_object(one_id)
obj_one

```

```{r}
ids <- head(res_search$object_id, 10)
obj_many <- met_objects(ids)
dplyr::glimpse(obj_many)

```

```{r}
plot_df <- obj_many %>%
  filter(!is.na(department)) %>%
  count(department, sort = TRUE)

plot_df

```
```{r}
ggplot(plot_df, aes(x = reorder(department, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(
    x = "Department",
    y = "Number of objects (sample)",
    title = "Objects by department (sample from search results)"
  )

```

```{r}
sessionInfo()

```

